const SUCCESSFUL_REQUEST_CODE = 200;

const SUCCESSFULL_POST_CODE = 201;

const BAD_REQUEST_STATUS_CODE = 400;

const REQUEST_NOT_FOUND_CODE = 404;

const INTERNAL_SERVER_ERROR_CODE = 500;

module.exports = {
  SUCCESSFUL_REQUEST_CODE,
  SUCCESSFULL_POST_CODE,
  BAD_REQUEST_STATUS_CODE,
  REQUEST_NOT_FOUND_CODE,
  INTERNAL_SERVER_ERROR_CODE,
};
