const SUCCESSFUL_REQUEST_CODE = 200;

const SUCCESSFULL_POST_CODE = 201;

const BAD_REQUEST_STATUS_CODE = 400;

const UNAUTHORIZED_STATUS_CODE = 401;

const FORBIDDEN_STATUS_CODE = 403;

const REQUEST_NOT_FOUND_CODE = 404;

const CONFLICT_ERROR = 409;

const INTERNAL_SERVER_ERROR_CODE = 500;

module.exports = {
  SUCCESSFUL_REQUEST_CODE,
  SUCCESSFULL_POST_CODE,
  BAD_REQUEST_STATUS_CODE,
  REQUEST_NOT_FOUND_CODE,
  INTERNAL_SERVER_ERROR_CODE,
  UNAUTHORIZED_STATUS_CODE,
  FORBIDDEN_STATUS_CODE,
  CONFLICT_ERROR,
};
